### ISSUE TITLE
Privacy considerations regarding the mapbox sku token

### ISSUE THREAD

**Issue by rufposten** [ev-map/EVMap#141]
Hi, I just made a short privacy check for the app. While it's really privacy friendly compared to all the charging apps, I found a ID attached to every mapbox call, the so called "[sku token](https://docs.mapbox.com/help/glossary/sku-token/)". 

`https://api.mapbox.com/fonts/v1/mapbox/DIN%20Offc%20Pro%20Regular%2cArial%20Unicode%20MS%20Regular/256-511.pbf?access_token=pk.abcdefghijk123456789&sku=100kuya9kxy4977079c7b3449b0975364ae06e21266`

A [scandal from 2019](https://www.nytimes.com/interactive/2019/12/19/opinion/location-tracking-cell-phone.html) shows how problematic a collection of pseudonymous location data could be, so I tried to take a closer look. 

I didn't find many information on the token. Here is a mapbox function [createSkuToken()](https://github.com/mapbox/mapbox-gl-js/blob/992514ac5471c1231d8a1951bc6752a65aa9e3e6/src/util/sku_token.js) showing how it's generated, but I can't tell if this is really belonging to the SDK you are using.

This source code states, that the token changes every 12 hours, but in my test the changes are so subtle that a user still could be tied to it's former ID:

19.10.2021 / 19:30: `sku=100kuyd42em7d79922aa4764ddfae1155a13a350d0d`
20.10.2021 / 09:42: `sku=100kuz7dog97d79922aa4764ddfae1155a13a350d0d`

I also tried to change the [telemetry setting on the mapbox map](https://docs.mapbox.com/help/getting-started/attribution/) in your app, but this didn't alter the sku attachment. 

Does anyone have any ideas or further information on this?

**Comment by rufposten** [comment]
So with the dummy implementation, will there still be attached sku's? 

I just checked streetcomplete, they use jawg.io and this works without pseudonymous IDs:
`GET https://tile.jawg.io/streets-v2/16/34870/22743.pbf?access-token=mL9X4SwxfsAGfojvGiion9hPKuGLKxPbogLyMbtakA2gJ3X88gcVlTSQ7OD6OfbZ& HTTP/2.0`

**Comment by rufposten** [comment]
If this helps .. I just checked Transportr - this FOSS app also uses Mapbox and doesn't attach sku's:

`GET https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7/4/8/4.vector.pbf?access_token=abcdefg123456&events=true HTTP/1.1`

Probably because of [deactivating telemetry](https://github.com/grote/Transportr/blob/fb7682f0fb4288e8187280351693cb708e939fdd/app/src/main/java/de/grobox/transportr/TransportrApplication.kt) instead of excluding the modules?:
`MapboxTelemetry.getInstance().isTelemetryEnabled = false`

**Comment by johan12345** [comment]
This is the first response from my contact at Mapbox that I received, I‘m still waiting for a reply from the technical team:

> - You are correct that the SKU is to count MAUs, that is all. More here: https://docs.mapbox.com/android/maps/guides/pricing/ and https://docs.mapbox.com/help/glossary/sku-token/ .
> - We do not track individuals' movement data overtime. Our telemetry pipeline is separate from the usage/MAU tracking. Our telemetry collection also anonymizes and chops up all movement data at the source so it is not possible to trace an individual cellphone's journey over time. More on telemetry data privacy here: https://www.mapbox.com/telemetry/ 
> - For more on Mapbox and privacy: https://www.mapbox.com/legal/privacy

(MAU = monthly active user)
