### ISSUE TITLE
Add details about voltage and amperage of chargers

### ISSUE THREAD

**Issue by johan12345** [ev-map/EVMap#151]
It would be helpful to add information about maximum voltage and amperage of chargers (e.g. to differentiate what power a DC charger can deliver to 400V vs. 800V vehicles).

This data is currently not available through the GoingElectric API (or actually, it is available, but only with the API key used by the web frontend - 3rd party applications do not get the data).

OpenChargeMap does provide this data.

**Comment by fhvyhjriur** [comment]
Implementing it for OpenChargeMap and making its datasource better (contributing to OpenChargeMap in germany) would be a functional solution at the moment.
