### ISSUE TITLE
Android Auto/Automotive: think about more prominent way to show plugs and availability

### ISSUE THREAD

**Issue by johan12345** [ev-map/EVMap#198]
On cars with larger screens (e.g. Android Automotive OS cars), we could think about showing plugs and availability in a more prominent way in the same layout as in the app. That way they would be more easily glanceable. However this is probably only possible by generating an image and overlaying it on top of the charger photo. Also, I think it is not easily possible to detect how large the car screen is.

Suggested by @greentux on the [goingelectric forum](https://www.goingelectric.de/forum/viewtopic.php?p=1887073#p1887073)

**Comment by PulsarFX** [comment]
maybe show the available stalls in the pin marker itself?
Power is already coded via color, text could be used for availability.

**Comment by johan12345** [comment]
Not really possible as AA's templates don't have much flexibility in customizing the marker icon... Also, the markers already contain a text (number) used for matching them to the entries in the list.

**Comment by PulsarFX** [comment]
ah right. I just thought of the app display :D

**Comment by johan12345** [comment]
that is #166 ;)

**Comment by johan12345** [comment]
Since c8f333c we're using the plug icons here instead of texts. Making it larger or generating a large image and showing it inline with the text is not really possible with the Car App Library, so I'll close this for now.
