### ISSUE TITLE
Google Play Protect blocks latest versions from installing

### ISSUE THREAD

**Issue by PeterKW** [ev-map/EVMap#270]
https://f-droid.org/repo/net.vonforst.evmap_164.apk

V1.4.8 apk seems to be blocked by Google Play Protect?

I will try and screenshot the message from Google

**Comment by PeterKW** [comment]
![Screenshot_20230225-132503.png](https://user-images.githubusercontent.com/13779157/221359423-28c833ac-a186-44ce-9dc8-a6e6fca946ff.png)

**Comment by johan12345** [comment]
Thanks for the info! I filed a complaint with Google at https://support.google.com/googleplay/android-developer/contact/protectappeals. Unfortunately there's not much else I can do here, as I don't know what type of data Play Protect is referring to here. I've also never received a similar warning about the Google Play version of the app...

See also https://gitlab.com/fdroid/fdroiddata/-/issues/2859 for a similar issue with another app on F-Droid.

You can also always obtain the APK through the releases page here on GitHub. That one is not signed with F-Droid's key, maybe that is enough for Play Protect to accept it?

**Comment by johan12345** [comment]
Did not hear about any other cases of this, and I think apart from the appeal I sent there's nothing else I can do to fix it - so closing this issue for now.
