### ISSUE TITLE
Crash when viewing chargers with pictures

### ISSUE THREAD

**Issue by celsoazevedo** [ev-map/EVMap#271]
Hey,

The app is crashing when viewing some chargers from Open Charge Map. It doesn't happen right away or even always, but when it happens it seems to be on entries with pictures. I'm not completely sure, but it seems to crash after the app downloads the high resolution files? (I could be wrong.)

Initially I thought it was caused by the custom ROM I use (LineageOS 20/Android 13), but it also happens on a friend's phone, which runs 100% stock software (OnePlus' OxygenOS/Android 13).

The crash happens on both the F-Droid and the Play Store's versions of the app. I couldn't make it crash when using GoingElectric.de as source, but to be honest, they're missing most chargers around here and I never used it as much as OCM. The two chargers I clicked on the screen recording below are:

- OCM-167009: https://openchargemap.org/site/poi/details/167009
- OCM-238155: https://openchargemap.org/site/poi/details/238155

Video:

https://user-images.githubusercontent.com/4492221/226443453-275a98cc-0bea-4b09-8e16-88348797c648.mp4

**Comment by johan12345** [comment]
Hi, thanks for the bug report! Did you already send the crash report via email as suggested by the app?

**Comment by johan12345** [comment]
Should be fixed with https://github.com/ev-map/EVMap/commit/f8d5b781129529c3306e624de61af20c8068add3 - I think this `SizeResolver(OriginalSize)` was neeeded earlier to make animations work correctly, but is now apparently unnecessary. If I remove it, the image is scaled down according to the `ImageView` size before being displayed, so it doesn't crash even if the original image is very large.

**Comment by celsoazevedo** [comment]
Thanks Johan. I'll test when the next update is released and report back if I find any issues.

**Comment by johan12345** [comment]
The update to 1.4.9 is now uploaded - it should be available within a couple of days on both Google Play (after Google's review) and F-Droid (when their build server picks it up during the next sync).

**Comment by celsoazevedo** [comment]
I've tested with the apks from this release and it seems to be working well. No crashes.

Thanks again for fixing this and for your work on the app.

**Comment by johan12345** [comment]
Great, thank you for testing! 👏🏻
