### ISSUE TITLE
Better OpenChargeMap support

### ISSUE THREAD

**Issue by celsoazevedo** [ev-map/EVMap#273]
Hey,

Assuming it's possible, it would be nice if EVMap displayed more info when using OpenChargeMap as data source.

Some entries have information about parking restrictions, notes about how we can pay for the charger, a link to the charger's website where we can see the real time status/prices, etc. For example, OCM-235945:

<img width="400" alt="Screenshot 2023-04-16 at 23 58 57" src="https://user-images.githubusercontent.com/4492221/232347736-8a89a914-a276-4b9d-a122-eeca4ca4bc9a.png">

<img width="400" alt="Screenshot 2023-04-16 at 23 59 06" src="https://user-images.githubusercontent.com/4492221/232347750-55f33f0f-4e07-40a2-82d3-6303ba5ac38c.png">

They also support comments, which can be useful when looking for feedback about the charger/location. Perhaps some "tab" to display the comments/photos could be created (similar to plugshare, zapmap, etc)?

Some status are also not correctly displayed by EVMap. For example, OCM-237231 is a duplicated entry/doesn't exist and is marked as "Operational Status: Removed (Duplicate Listing)". OCM displays this:

<img width="400" alt="Screenshot 2023-04-16 at 23 54 23" src="https://user-images.githubusercontent.com/4492221/232348011-f9f5c042-4d36-4b7f-8218-4fdd39de13af.png">

While EVMap displays the charger as if it's working:

<img width="400" alt="Screenshot_20230417-000438_EVMap" src="https://user-images.githubusercontent.com/4492221/232348659-3c9d1190-3179-43ba-8c10-0cd5883f4ca5.png">

I don't know if it's because the entry is "Removed (Duplicate Listing)", but the charger itself is "Operational"? Maybe they should sites marked as duplicated, but since the quality of the data will sometimes be like this, I think it's a good idea to handle it better.

**Comment by johan12345** [comment]
Thanks! Yes, we should investigate whether these details are available through the OCM API (probably yes) and then map them to the existing internal data structure or add extra fields.
I think we're currently not filtering by charger status by default, we should definitely not show deleted chargers.

**Comment by johan12345** [comment]
> Some entries have information about parking restrictions, notes about how we can pay for the charger

These are already included, see the screenshot below:
<img src="https://user-images.githubusercontent.com/5310424/233434121-e5b5b638-9bb8-435f-814d-676740e18d48.png" width="200" />

> a link to the charger's website where we can see the real time status/prices

will add it in the next update: c5714c859267341aa09b0fcb763ba09f765aa775

> They also support comments, which can be useful when looking for feedback about the charger/location. Perhaps some "tab" to display the comments/photos could be created (similar to plugshare, zapmap, etc)?

Yeah, that is possible but a bit more work to implement in the UI. Currently we only show fault reports, other comments are not displayed. Let's divide it into a separate issue -> #277 

> Some status are also not correctly displayed by EVMap. For example, OCM-237231 is a duplicated entry/doesn't exist and is marked as "Operational Status: Removed (Duplicate Listing)"

will hide deleted chargers in the next update: fab66d1f84aab3e2ae5660670fad214cd27064a3
