### ISSUE TITLE
Add support for live update of free chargers in an area

### ISSUE THREAD

**Issue by dexic79** [ev-map/EVMap#279]
Hi@all!

Would it be hard to add some kind of live update of free chargers in an area? I have it all the time. When I depart, I know where the nearest charger to my destination is. When I arrive, it is occupied. Stuttgart has it often enough... Now, would it be possible to pick one charger and have the chargers in vincinity be checked if they are free, too, so I can move fast to the next one? I would like to do the following steps:

- turn on filter
- Type my destination address, where I want to go to.
- see the availability with little markers on the location markers like red, green and grey (not available). This would be fast and easy to see and adjust accordingly.
- The app has to update this area in the background, obviously, so when I get it back from background when I think of it, I have good data. Perhaps a 5 min split would work, if the API can "swallow" it. 
- If the nearest charger would be occupied by now, it would show red, but the others around my destination would perhaps be free and I could simply use the pin and then navigation button to then take the next one easily, while driving or stopping at a red signal.

If I mark the nearest charger as temporary navigation "mark", it would be nice to see a message on the screen, if it is occupied or goes back to available, so I can adjust my route accordingly before passing by. This would be really helpful. :-) 

Thank you for the great app! I like it very much for the clear UI and the good filters. :-) I just want it to be a little bit more helpful when really needed. :-)

**Comment by johan12345** [comment]
Hi, thanks for the suggestion!
A combination of #166 and #42 would basically cover this use-case, right?

**Comment by johan12345** [comment]
closing as it seems to be a duplicate and the original poster did not repond
