### ISSUE TITLE
Android Auto: Check out SuggestionManager

### ISSUE THREAD

**Issue by johan12345** [ev-map/EVMap#283]
https://developer.android.com/reference/androidx/car/app/suggestion/SuggestionManager
-> might show recently viewed charging stations, or favorites that are nearby?

Not sure if this is only available for navigation apps though

**Comment by MartinH-open** [comment]
Hmm, it is documented as:
throws HostException ..
"if the call is invoked by an app that is not declared as a navigation app in the manifest"
but I could not find this check implemented in the current source code ...

**Comment by johan12345** [comment]
yeah, seems like it's only available for navigation apps so far 😞  Reported as a feature request: https://issuetracker.google.com/issues/286928903
