### ISSUE TITLE
Option to disable cache

### ISSUE THREAD

**Issue by celsoazevedo** [ev-map/EVMap#287]
I've been updating outdated chargers and adding new ones to OCM. Depending on what I am doing, sometimes I use EVMap (since their app is not the fastest) to quickly edit the entry, check if changes look okay, etc, or compare the map entries with other databases.

The "problem"? Since cache was introduced, I have to keep purging it to see changes right away.

This doesn't affect most users and it's not something that must be implemented, but it would be nice to have a way to disable caching for situations like this.

**Comment by johan12345** [comment]
Hmm, I'm not sure if I would want to add an option to globally disable the cache as that would negate the benefits of caching (reduced server load and better performance on slow networks).

Would a refresh button that forces the app to reload the currently viewed charger or map area from the server also be a solution?

**Comment by celsoazevedo** [comment]
I guess that could work. Or if you want to hide this from most users, maybe a setting inside the hidden developer menu since this would be mostly for "debugging"?

Anything would be fine.

**Comment by celsoazevedo** [comment]
@johan12345 Tested this on 1.6.5 and it seems to be working. Thanks again for implementing it.

Two notes:

![menu](https://github.com/ev-map/EVMap/assets/4492221/067980fe-fc5c-48e9-bebc-0d8231b06bb1)

- The text in the "popup" menu in the charger view doesn't charge with the theme change, so dark theme = dark text.
- For consistency sake, maybe "edit on..." should start with a capital letter?
