### ISSUE TITLE
Wrong route availability in EVmap

### ISSUE THREAD

**Issue by programmin1** [ev-map/EVMap#294]
The major highways are green even when the highway is blocked - for example, the route between Grants Pass and Crescent city is blocked as of now at California-Oregon border, but that doesn't show in the app, it shows green highways.

![Screenshot from 2023-08-22 20-56-03](https://github.com/ev-map/EVMap/assets/1295242/f056ae0c-4258-406b-a34a-4fb787419ef8)

**Comment by johan12345** [comment]
Are you using Google Maps or Mapbox as the base map data source? The traffic data also comes from there so please report it to the data source.
