### ISSUE TITLE
Migrate to kts build script

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#297]
From gradle 4.0, it's possible to using to Kotlin DSL for gradle scripts. Using this language is better because Android Studio doesn't support syntax highlighting for Groovy. And using this language improve build performance.

More information here https://developer.android.com/build/migrate-to-kotlin-dsl#:~:text=Starting%20with%20Android%20Studio%20Giraffe%2C%20new%20projects%20use%20the%20Kotlin,completion%2C%20and%20navigation%20to%20declarations.
https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html

I can help for migration :)
I have already doing migration for [Exodus app](https://github.com/Exodus-Privacy/exodus-android-app/pull/333/commits/dd85cff365aede1237fe2f6c3f6cfd19014279b2)

**Comment by johan12345** [comment]
Hi, thanks for the suggestion. I don't have a strong preference between Groovy and Kotlin for the Gradle scripts at the moment. Is Kotlin actually faster though? [This](https://github.com/gradle/gradle/issues/15886#issuecomment-1432923669) seems to show quite the opposite...

**Comment by orubel** [comment]
I think they have already accepted that it is going to be slower :)
![android](https://github.com/ev-map/EVMap/assets/274764/aefa11a1-f020-4d5d-bd5c-37db31fc779c)

**Comment by johan12345** [comment]
Implemented with #298, with only negligible effect on build times. Thanks @Jean-BaptisteC!

**Comment by orubel** [comment]
> Implemented with #298, with only negligible effect on build times. 

Yeah, non-abi would not be effected from what I am seeing.
