### ISSUE TITLE
Chargepoint Marker hidden behind maps markers

### ISSUE THREAD

**Issue by PulsarFX** [ev-map/EVMap#299]
![Screenshot_20231001_160933_EVMap~01](https://github.com/ev-map/EVMap/assets/4960210/a03176aa-0b04-4a70-96aa-8db11830c943)

The marker for the charging stations are hidden beneath gmaps markers.

**Comment by johan12345** [comment]
This seems to be only when the traffic layer is enabled, correct?
I will check whether I can do anything about that or if it's an error on the Google Maps SDK side.

**Comment by johan12345** [comment]
Increasing the marker's `zIndex` unfortunately didn't help.
Seems like the inability to influence the drawing order for the traffic layer is a long-running issue in the Google Maps SDK: https://issuetracker.google.com/issues/35824192 - I've just added a comment there that it affects markers as well. Other than that - I guess there's nothing I can do about it at the moment 😐

**Comment by johan12345** [comment]
Ah, there is a new Google Maps SDK update that introduces [`AdvancedMarker`](https://developers.google.com/maps/documentation/android-sdk/advanced-markers/overview) with some more options about overlap with other map items. I will check if this helps.

**Comment by johan12345** [comment]
closing this - as I said, there seems to be no way to solve it on EVMap's side without causing additional costs, unless Google changes something.
