### ISSUE TITLE
Android Auto for phone screens is not available in Play Store

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#303]
https://github.com/ev-map/EVMap/blob/master/doc/android_auto.md#install-android-auto
In this docs, this [link](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead.phonescreen) is not available

**Comment by johan12345** [comment]
Thanks! Yeah, the "Android Auto for phone screens" app was deprecated, so the link probably only works if you had previously installed it. But I updated the docs to now show a different way to access the Android Auto settings without needing the "Android Auto for phone screens" app.
