### ISSUE TITLE
Weird status info

### ISSUE THREAD

**Issue by Altonss** [ev-map/EVMap#310]
I have some cases (like the one below), where the status display is weird.
Version 1.7.1 (F-Droid)
![image](https://github.com/ev-map/EVMap/assets/66519591/1931df1e-c9e8-4e0e-a138-7cbe075295bb)

**Comment by johan12345** [comment]
This indicates that at least one of the 150 kW connectors has an unknown status. That usually means the charger did not send updates to the backend, so it's probably offline, but might still be working. In #308 I will add a detail view when tapping on the connectors, which will make this more clear.

**Comment by johan12345** [comment]
Yes, the 2 is the number of online and available connectors - of the other two, at least one has unknown status. The new detail view will fix that ambiguity, then you will be able to see the status for each individual connector.

**Comment by johan12345** [comment]
The detail view has been added in the 1.8.0 update, so this should be clearer now (tap on the connector to see the status for each single plug).
