### ISSUE TITLE
Add support for openchargemap.io links

### ISSUE THREAD

**Issue by Altonss** [ev-map/EVMap#313]
For now only openchargemap.org support can be added, but when sharing a charger, an openchargemap.io link gets created.

**Comment by johan12345** [comment]
Thank you! 🙂

**Comment by johan12345** [comment]
Hmm, you mean when you click the "Source: OpenChargeMap.org" or "Edit at OpenChargeMap.org" buttons in EVMap, it just opens the same charger again within EVMap? Yeah, that is a problem...

There is already workaround implemented, but currently it only works with browsers that support ["Custom Tabs"](https://developer.chrome.com/docs/android/custom-tabs) (Chrome, Firefox, Edge and a few others). You're probably using a different one? I can try if I can make it work with other browsers as well...
