### ISSUE TITLE
Position of slider is updated on Compare cost fragment.

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#328]
How reproduce:
- Start app
- Select node of app with compare button
- Touch compare cost button -> Position of slider is updated after screen is opened

**Comment by johan12345** [comment]
I'm not quite sure what you mean here, can you share some screenshots or a screen recording?

**Comment by Jean-BaptisteC** [comment]
https://github.com/ev-map/EVMap/assets/87148630/a40eb9d1-fbf6-4cc5-b140-843633d7f29f
