### ISSUE TITLE
Use generateLocaleConfig gradle feature

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#330]
With latest versions of gradle 8.0, gradle can automatically generate [locale config file](https://github.com/ev-map/EVMap/blob/master/app/src/main/res/xml/locales_config.xml)

More information here:
- https://developer.android.com/guide/topics/resources/app-languages#auto-localeconfig

**Comment by johan12345** [comment]
The two links are the same, I suppose one of them was supposed to link to some documentation?
But it is true that I forgot to manually update this file as we added more languages... 🙈

**Comment by Jean-BaptisteC** [comment]
Updated 😂

**Comment by johan12345** [comment]
Thanks! Yes, this sounds useful, would be nice if you can add it.

We have to check though whether the automatic generation will include just the locales that EVMap itself supports (listed in `supportedLocales` in the `build.gradle.kts` file), or also add all that 3rd party libraries might include.

**Comment by Jean-BaptisteC** [comment]
Yes, that's the case, AGP checks translations in your app to keep only libraries translations necessary and supportedLocales property is not longer use.
