### ISSUE TITLE
Error message is not synced with app theme

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#336]
![Screenshot_20240427-173532](https://github.com/ev-map/EVMap/assets/87148630/e6dd78a1-fa3d-467f-9d7e-18257907be9a)

**Comment by Jean-BaptisteC** [comment]
Error message cannot be synced with theme app.
I have in another project.

**Comment by johan12345** [comment]
I did find a solution that looks a bit nicer

**Comment by Jean-BaptisteC** [comment]
Nice
