### ISSUE TITLE
App shortcut doesn't work

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#338]
How reproduce:
- On app launcher, doing a long press on app icon
- Press favorites item -> Toast app is not installed

Problem is maybe caused because the name of class was called doesn't have the same path class has the app_id?

I have see your comments in shortcuts.xml

Version 1.8.2.Google

**Comment by johan12345** [comment]
I was using the [resourcePlaceholders](https://github.com/timfreiheit/ResourcePlaceholdersPlugin) gradle plugin (or [a more recent fork](https://github.com/extmkv/ResourcePlaceholdersPlugin)) to try and automatically fill in the app ID into `shortcuts.xml`. But it does not seem to be not working with the latest Android Gradle Plugin version - upgrading the plugin did not fix it.

So with https://github.com/ev-map/EVMap/commit/862f2b06d8594f7ce56f83df58e3764ffab28bbf I reverted to hardcoding the app ID. This should fix the problem in the next release, but it will not work in the debug version of the app, as I use a separate package name for that.
