### ISSUE TITLE
Update app screenshots on Google Play

### ISSUE THREAD

**Issue by Jean-BaptisteC** [ev-map/EVMap#341]

**Comment by johan12345** [comment]
Thanks for noticing - I just uploaded the latest ones from the repo, they should appear in Google Play in the next few days.

There is a branch `screenshots` in which I tried to automate screenshot generation with an emulator running on GitHub Actions. Then we could automatically make new screenshots for each release with every form factor and in every supported language.
But unfortunately it was not working reliably so far. I'll create a draft PR so you can see it.
