### ISSUE TITLE
Map goes away - unusable

### ISSUE THREAD

**Issue by programmin1** [ev-map/EVMap#346]
I open EVMap (1.9.1) and it's fine, I can browse around.

I leave and open it again, and the map is entirely a black box. Nothing shown zooming or scrolling.
Swipe it away and then open anew and then the app shows a map again.

Teracube with /e/OS 2.0 (which is Android 12)

**Comment by programmin1** [comment]
Still seeing the same issue on 1.9.2.

**Comment by johan12345** [comment]
The fix is in 1.9.3.
