### ISSUE TITLE
Some markers disapper on zoom

### ISSUE THREAD

**Issue by arminfuerst** [ev-map/EVMap#351]
With the recent version, I have the effect of markers (seems as only the yellow ones) are disappearing if I zoom to the level where the markers change from the circle icon to the pin icon.
Screenshot (low res) with a zoom where all markers are still visible:
![Screenshot_20240615-185417_EVMap_small](https://github.com/ev-map/EVMap/assets/29121472/57c70f95-e605-42f3-8a84-2e5eb23d22d5)
Screenshot (low res) of the same area with a slightly higher zoom, I marked where I expect the pins with red circles:
![Screenshot_20240615-185427_EVMap_small](https://github.com/ev-map/EVMap/assets/29121472/d561d05b-7255-41ae-ad5c-038f410f2c0e)

Here are the same screenshots in original resolution if needed:
![Screenshot_20240615-185417_EVMap](https://github.com/ev-map/EVMap/assets/29121472/bce9bfde-20c0-4cf4-8a81-bdb64bc74531)
![Screenshot_20240615-185427_EVMap](https://github.com/ev-map/EVMap/assets/29121472/b2f1d69a-f97b-4310-ad69-9e266adcb5f7)

**Comment by arminfuerst** [comment]
After clearing the cache and made a "force stop" of the app, the pin markers are displayed properly again.

**Comment by johan12345** [comment]
I have managed to reproduce this once, but not yet reliably.

There is a recent new [MapLibre release](https://github.com/maplibre/maplibre-native/releases/tag/android-v10.3.2-pre2) which mentions a fix regarding "symbols disappearing randomly", I will try to update to that one - let's see if it helps.

**Comment by johan12345** [comment]
I haven't seen this anymore with version 1.9.4 or 1.9.5, please let me know if it still occurs.
