### ISSUE TITLE
Chargeprice price displayed despite not available in country

### ISSUE THREAD

**Issue by Altonss** [ev-map/EVMap#355]
On a charger in France, I get this provider displayed: `Pay Per User (Italy) / Enel X Way  [(i) Only if country "Italy" is selected]`.
I don't know if there is anything that can be done on the EVMap side to filter this out from the chargeprice API, but it is stange to see prices in the list that are in fact not possible.
![image](https://github.com/user-attachments/assets/785f0ae2-5c2d-4f7c-b056-5fc014dc8e89)

It's a really a minor issue related to chargeprice, so no worries if EVMap can't do much :)

**Comment by johan12345** [comment]
If I understand this correctly, that notice refers to having to have "Italy" selected as the country of your user account in the Enel X Way app - not necessarily that the price only applies to chargers located in Italy.

But if that's not correct - yes, that's something that would have to be fixed on Chargeprice's side (and I'd expect the same to happen on their website).

They have a button to report incorrect prices on their website :)
