### ISSUE TITLE
Wrong connector name + missing icon: SCAME Type 3C (Schneider-Legrand) 

### ISSUE THREAD

**Issue by Altonss** [ev-map/EVMap#356]
On this charger https://map.openchargemap.io/?id=166489 (just an example), the name of the SCAME Type 3C (Schneider-Legrand) connector is somehow renamed as Type 3A and is missing an icon.

**Comment by johan12345** [comment]
Right, I think when I initially set this up I was confused about the difference between Type 3A and Type 3C (which are not used here in Germany), especially as GoingElectric's API doesn't clearly separate them (even though the website does now). I'll fix this.

**Comment by johan12345** [comment]
for the missing icon, see #6
